name: smile_identity_plugin
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://google.com/

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tembo_plus.smile_identity_plugin
        pluginClass: SmileIdentityPlugin
      ios:
        pluginClass: SmileIdentityPlugin

