name: smile_identity_plugin
description: Wraps official iOS and Android SmileIdentity SDKs.
version: 0.0.1+2
homepage: https://github.com/okellogerald/smile_identity_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  plugin_platform_interface: ^2.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.smile.smile_identity_plugin
        pluginClass: SmileIdentityPlugin
      ios:
        pluginClass: SmileIdentityPlugin

